Modernize usage and support for public key cryptography
bloomberg/ntf-core pull request #158
Opened 2024-05-22 19:11 UTC by mattrm456

This PR introduces a significant number of changes to modernize the usage and support for public key cryptography, as used by ntci::StreamSocket to allow a user to upgrade into and out of TLS sessions. This PR has several goals:

1) Support generation of more than just RSA private keys, namely, the SEC-endorsed named elliptic curves such as "secp256r1".

2) Support user-defined validation of a peer's certificate. Practically speaking, to make any reasonable decision about the validity of a certificate, the structure and values in the certificate must be transparent. This PR adds value-semantic representations of certificates and private keys (ntca_encryptioncertificate and ntca_encryptionkey)  and capability to encode and decode certificates and private keys according to the Distinguished Encoding Rules (DER).

3) Support additional, built-in certificate validation parameters such as subject common name and subject alternative name matching.

4) Support TLS clients issuing a "server name indication" when they initiate the TLS session handshake, to request a particular sub-configuration of the TLS server peer, and support TLS servers optionally specifying name-specific certificates and key they should use when clients indicate the associated name.

5) Support configuring TLS clients and TLS servers with certificates and keys in more than just ASN.1/PEM-encoded files. Support now includes ASN.1, PKCS7, PKCS8, PKCS12, and optionally subsequent wrapping in PEM of most of the formats.

6) Support for a user-defined mechanism to resolve a shared secret on-demand, when decoding something like a PKCS8 file that has been symmetrically encrypted.

2024-05-23 11:29 UTC, smtrfnv requested changes
It's unbuildable on Windows at least.

> C:\bloomberg\ntf-core\groups\ntc\ntca\ntca_encryptioncertificate.cpp(2307): error C2065: 'NL_TEXTMAX': undeclared identifier

> C:\bloomberg\ntf-core\groups\nts\ntsa\ntsa_abstract.cpp(788): error C2220: the following warning is treated as an error
> C:\bloomberg\ntf-core\groups\nts\ntsa\ntsa_abstract.cpp(788): warning C4244: 'argument': conversion from 'const uint64_t' to 'uint8_t', possible loss of data
> C:\bloomberg\ntf-core\groups\nts\ntsa\ntsa_abstract.cpp(5366): warning C4244: 'argument': conversion from 'uint64_t' to 'BloombergLP::ntsa::AbstractIntegerRepresentation::Block', possible loss of data

2024-05-23 18:52 UTC, mattrm456 commented on groups/ntc/ntca/ntca_encryptionoptions.h
> +class EncryptionOptions
Strictly speaking, unless the implementation needs to retain the basic allocator as a member for later direct use to dynamically allocate memory consistent with the lifetime of the object, the policy is to simply forward `basicAllocator` to each allocator-aware member.

2024-05-23 18:54 UTC, mattrm456 commented on groups/nts/ntsa/ntsa_abstract.h
> +// Copyright 2020-2023 Bloomberg Finance L.P.
Let's universally bump the year when we do the next release, and henceforth plan to do this on Jan 1 of 2025.

2024-05-23 18:55 UTC, mattrm456 commented
I fixed the warnings-as-errors on Windows with stricter static_casts.

2024-05-27 07:42 UTC, smtrfnv approved these changes
It's amazing how well structures and carefully designed this PR is. Let's merge it. Just don't forget to fix GitlabActions failure.

2024-05-28 18:01 UTC, mattrm456 commented
GitHub Actions are now all successful.

2024-05-28 18:02 UTC, merged