Implement asynchronous socket detachment for reactors and proactors
bloomberg/ntf-core pull request #55
Opened 2023-06-20 14:08 UTC by smtrfnv

This PR implements asynchronous socket detachment mechanism for existing reactor and proactor drivers.

`ntci::Reactor` is extended with new methods, existing detachment methods are marked deprecated:
```
    /// Stop monitoring the specified 'socket'. Return the error.
    BSLS_DEPRECATE_FEATURE("ntci",
                           "socket-detachment",
                           "use callback version instead")
    virtual ntsa::Error detachSocket(
        const bsl::shared_ptr<ntci::ReactorSocket>& socket) = 0;

    /// Stop monitoring the specified 'socket'. Invoke the specified 'callback'
    /// when the socket is detached. Return the error.
    virtual ntsa::Error detachSocket(
        const bsl::shared_ptr<ntci::ReactorSocket>& socket,
        const ntci::SocketDetachedCallback&         callback);

    /// Stop monitoring the specified socket 'handle'. Return the error.
    BSLS_DEPRECATE_FEATURE("ntci",
                           "socket-detachment",
                           "use callback version instead")
    virtual ntsa::Error detachSocket(ntsa::Handle handle) = 0;

    /// Stop monitoring the specified socket 'handle'. Invoke the specified
    /// 'callback' when the socket is detached. Return the error.
    virtual ntsa::Error detachSocket(ntsa::Handle handle,
                                     const ntci::SocketDetachedCallback& callback);
```

`ntci::Proactor` is updated in a similar way:
```
    /// Detach the specified 'socket' from the proactor. Return the error.
    BSLS_DEPRECATE_FEATURE("ntci",
                           "socket-detachment",
                           "use detachSocketAsync instead")
    virtual ntsa::Error detachSocket(
        const bsl::shared_ptr<ntci::ProactorSocket>& socket) = 0;

    /// Detach the specified 'socket' from the proactor. The specified 'socket'
    /// will be notified when it's detached. Return the error.
    virtual ntsa::Error detachSocketAsync(
        const bsl::shared_ptr<ntci::ProactorSocket>& socket) = 0;
```

Socket autoAttach/Detach funtionality may conflict when it is used together with new asynchronous detachment mechanism.

All existing socket implementations are using this new mechanism.

2023-07-31 15:32 UTC, smtrfnv commented on groups/ntc/ntci/ntci_proactorsocket.h
> +    bsls::AtomicUint      d_detachState;
TODO: probably I should use the context instead of extending the base class

2023-07-31 15:43 UTC, smtrfnv commented on groups/ntc/ntci/ntci_proactorsocket.h
> +    //TODO: can I just do return --d_processCounter and return the resulting value?
TODO: still a todo

2023-08-01 12:05 UTC, smtrfnv commented on groups/ntc/ntcp/ntcp_streamsocket.cpp
> +    }  // TODO: or it's better to defer it?
TODO: to be discussed

2023-08-01 12:23 UTC, smtrfnv commented on groups/ntc/ntcr/ntcr_streamsocket.cpp
> +            //TODO: should I wait for detachment to finish before releasing reactor reference?
TODO

2023-09-18 14:40 UTC, mattrm456 requested changes
Rename `ntcs::RegistryEntry::addOngoingProcess()` to `ntcs::RegistryEntry::incrementProcessCounter()` to lexically pair with `ntcs::RegistryEntry::decrementProcessCounter()`.

Refactor conditions expressed as `(entry->processCounter() == 0)` by adding a new function, `ntcs::RegistryEntry::isProcessing() const { return (this->processCounter() == 0); }`.

Combine `ntcs::RegistryEntry::askForDetachmentAnnouncementPermission()` with `ntcs::RegistryEntry::announceDetached()` (which currently returns `void`) so that `ntcs::RegistryEntry::announceDetached()` returns `bool` and effectively performs `ntcs::RegistryEntry::askForDetachmentAnnouncementPermission()` inside its body. This will make `announceDetached()` look and behave similar to `announceReadable()`, `announceWritable()`, etc.

Remove the `functor` parameter to `ntcs::Registry::removeAndGetReadyToDetach()` and simply require the caller to call whatever this is `functor` is bound to (e.g. `ntco::Epoll::removeDetached`) when this function returns. I think this enhances the readability of the detachment process by removing this indirection, which isn't currently used for any purpose.

The `ntcs::RegistryEntry::announceDetached()` function must protect its invocation and clearing of the d_detachCallback data member, similar to, e.g. `ntcs::RegistryEntry::announceWritable()`: Copy `d_detachCallback` to a local variable under the acquisition of `ntcs::RegistryEntry::d_lock`, release the lock, then invoke the callback on the copy.

2023-09-25 12:53 UTC, smtrfnv commented
> Rename `ntcs::RegistryEntry::addOngoingProcess()` to `ntcs::RegistryEntry::incrementProcessCounter()` to lexically pair with `ntcs::RegistryEntry::decrementProcessCounter()`.

 Done

> Refactor conditions expressed as `(entry->processCounter() == 0)` by adding a new function, `ntcs::RegistryEntry::isProcessing() const { return (this->processCounter() == 0); }`.

Done, in a way that `ntcs::RegistryEntry::isProcessing() const { return (this->processCounter() != 0); }`.
 
> Combine `ntcs::RegistryEntry::askForDetachmentAnnouncementPermission()` with `ntcs::RegistryEntry::announceDetached()` (which currently returns `void`) so that `ntcs::RegistryEntry::announceDetached()` returns `bool` and effectively performs `ntcs::RegistryEntry::askForDetachmentAnnouncementPermission()` inside its body. This will make `announceDetached()` look and behave similar to `announceReadable()`, `announceWritable()`, etc.

Done

> Remove the `functor` parameter to `ntcs::Registry::removeAndGetReadyToDetach()` and simply require the caller to call whatever this is `functor` is bound to (e.g. `ntco::Epoll::removeDetached`) when this function returns. I think this enhances the readability of the detachment process by removing this indirection, which isn't currently used for any purpose.

`functor` was moved back under a lock, where it should be.

> The `ntcs::RegistryEntry::announceDetached()` function must protect its invocation and clearing of the d_detachCallback data member, similar to, e.g. `ntcs::RegistryEntry::announceWritable()`: Copy `d_detachCallback` to a local variable under the acquisition of `ntcs::RegistryEntry::d_lock`, release the lock, then invoke the callback on the copy.

Done.

2023-11-01 13:32 UTC, mattrm456 approved these changes
I approve merging this PR, with the following statements.

This PR addresses a difficult problem in a complex codebase in a complex way. The changes introduced in this PR are not obviously incorrect, and all unit tests pass. However, these changes make an already complicated implementation of the sockets in `ntcr` and `ntcp` even more complicated.

We have a desire to converge into a simpler, more readable and maintainable implementation as this project evolves. This PR fixes a bug that is a real liability, especially in dynamically load balanced configurations. But it also increases the complexity of the implementation. On balance, I want first eliminate the liability, then reduce the complexity of the implementation. 

During the review of this PR, there have been several next steps identified that may prove fruitful in reducing the complexity of the implementation:

1) Eliminate the overload of `ntci::Reactor::detachSocket(ntci::ReactorSocket, ntci::SocketDetachedCallback` and simply have `ntci::Reactor::detachSocket` call a new virtual function `ntci::ReactorSocket::processSocketDetached`, which is more in alignment of the design of `ntci::ReactorSocket` and how detachment is currently observed for `ntci::ProactorSocket`. This will require non-trivial changes to the implementation of the `ntcr` sockets proposed in this PR.
 
2) Re-examine the shutdown sequence in `ntcr` sockets to eliminate special orderings and special cases of when, and how, sockets are detached from reactors and shutdown, especially with respect to the concern that some reactor implementation spin when polling a fully shut down socket.
 
3) Formalize how close callbacks are queued into `d_deferredCalls` in the `ntcr` socket implementations and eliminate the weird asynchronous behavior of the current PR with respect to these functors potentially ping-ponging between `d_deferredCalls` and the functor queue in `ntcs::Chronology` or `ntcs::Strand`.
 
4) Consider a modification of the "processing" reference counting strategy used by reactor implementations to maintain a reference count for as long as the socket is attached and not detaching.

5) Create more symmetry between the "context" stored by each reactor with the "context" stored by each proactor. For example, consider renaming `ntcs::RegistryEntry` to `ntcs::ReactorContext` and `ntcs::RegistryEntryCatalog` to `ntcs::ReactorContextCatalog`, with something similar for proactor sockets. Attempt to merge the atomic operations for different categories of state into a single 64-bit integer, rather than having separate CAS loops and spin locks.

6) Eliminate an unsafe race between threads calling `ntcs::ReactorSocket::getReactorContext` and `ntcs::ReactorSocket::setReactorContext`, and similarly for the proactor sockets.

2023-11-01 14:13 UTC, merged